name: rumor
version: 0.1.0.0
github: "exodrifter/rumor"
license: BSD3
author: "Ava Pek"
maintainer: "exodrifter@gmail.com"
copyright: "2019 Ava Pek"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis: Narrative scripting language for games
category: Language

description: Please see the README on GitHub at <https://github.com/exodrifter/rumor#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  rumor-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rumor
