name: rumor
version: 0.1.0.0
github: "exodrifter/rumor"
license: BSD3
author: "Ava Pek"
maintainer: "exodrifter@gmail.com"
copyright: "2019 Ava Pek"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis: Narrative scripting language for games
category: Language

description: Please see the README on GitHub at <https://github.com/exodrifter/rumor#readme>

ghc-options:
  - -XDerivingStrategies
  - -XGeneralizedNewtypeDeriving
  - -XOverloadedStrings
  - -Weverything
  - -Wcompat
  - -Wno-all-missed-specialisations
  - -Wno-missed-specialisations
  - -Wno-missing-exported-signatures # See https://ghc.haskell.org/trac/ghc/ticket/14794#ticket
  - -Wno-missing-import-lists
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-implicit-prelude

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- cryptonite
- hashable
- indents
- integer-gmp
- memory
- mtl
- parsec
- parsec3-numbers
- random
- safe
- text

library:
  source-dirs: src
  exposed-modules:
    - Rumor

tests:
  rumor-internal-test:
    main: Spec.hs
    source-dirs:
    - test-internal
    - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HUnit
  rumor-external-test:
    main: Spec.hs
    source-dirs:
    - test-external
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rumor
    - HUnit
