resolver: ghc-8.8.3
packages:
- .
extra-deps:
- basement-0.0.11
- call-stack-0.2.0
- cryptonite-0.27
- hashable-1.3.0.0
- HUnit-1.6.0.0
- indents-0.5.0.1
- memory-0.15.0
- parsec3-numbers-0.1.0
- random-1.2.0
- safe-0.3.19
- splitmix-0.1.0.1
